import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google"; // Import Inter and Roboto
import "./globals.css";
import Providers from "@/components/Providers";
import TopNav from "@/components/navbar/TopNav";

// Configure Inter font
const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter", // Define a CSS variable for Inter
});

// Configure Roboto font
// const roboto = Roboto({
//     weight: ["100", "300", "400", "500", "700", "900"], // Specify weights you need
//     subsets: ["latin"],
//     variable: "--font-roboto", // Define a CSS variable for Roboto
// });

export const metadata: Metadata = {
    title: "NextMatch",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        // Apply the font variables to the html tag
        <html lang="en" className={`${inter.variable} `}>
        <body>
        <Providers>
            <TopNav />
            <main className="container mx-auto p-10">
                {children}
            </main>
        </Providers>
        </body>
        </html>
    );
}
