import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google"; // Import Inter and Roboto
import "./globals.css";
import Providers from "@/components/providers/Providers";
import TopNav from "@/components/navbar/TopNav";
import {auth} from "@/auth";

// Configure Inter font
const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter", // Define a CSS variable for Inter
});


export const metadata: Metadata = {
    title: "NextMatch",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth();
    const userId = session?.user?.id || null;
    return (
        // Apply the font variables to the html tag
        <html lang="en" className={`${inter.variable} `}>
        <body>
        <Providers userId={userId}>
            <TopNav />
            <main className="container mx-auto">
                {children}
            </main>
        </Providers>
        </body>
        </html>
    );
}
